pipeline {
    agent any
    

    stages {
        stage('Build') {
            steps {
                echo "Building using maven"
            }
        }
        
        stage('Unit and Integration Tests') {
            steps {
                echo "Testing using JUnit"
            }
            post {
                failure {
                    script {
                        currentBuild.result = 'FAILURE'
                        emailext body: "Build failed. Check the attached log for details.",
                                 subject: "Build Status: FAILURE",
                                 attachmentsPattern: '**/*.log'
                                 to: "s222283975@deakin.edu.au"
                    }
                }
                success {
                    script {
                        currentBuild.result = 'SUCCESS'
                        emailext body: "Build succeeded. Check the attached log for details.",
                                 subject: "Build Status: SUCCESS",
                                 attachmentsPattern: '**/*.log'
                                 to: "s222283975@deakin.edu.au"
                    }
                }
            }
        }
        
        stage('Code Analysis') {
            steps {
                echo "using SonarQube tool to analyse the code."
            }
        }
        
        stage('Security Scan') {
            steps {
                echo "OWASP Dependency-Check Plugin"
            }

            post {
                failure {
                    script {
                        currentBuild.result = 'FAILURE'
                        emailext body: "Build failed. Check the attached log for details.",
                                 subject: "Build Status: FAILURE",
                                 attachmentsPattern: '**/*.log'
                                 to: "s222283975@deakin.edu.au"
                    }
                }
                success {
                    script {
                        currentBuild.result = 'SUCCESS'
                        emailext body: "Build succeeded. Check the attached log for details.",
                                 subject: "Build Status: SUCCESS",
                                 attachmentsPattern: '**/*.log'
                                 to: "s222283975@deakin.edu.au"
                    }
                }
            }
        }

        
        stage('Deploy to Staging') {
            steps {
                echo "Deploying to staging in AWS EC2 server"
            }
        }
        
        stage('Integration Tests on Staging') {
            steps {
                echo "using JUnit for Integration testing"
            }
        }
        
        stage('Deploy to Production') {
            steps {
               echo "Deploying to production in AWS EC2 server"
            }
        }
    }
}
