pipeline {
    agent any
    

    stages {
        stage('Build') {
            steps {
                echo "Building using maven"
            }
        }
        
        stage('Unit and Integration Tests') {
            steps {
                echo "Testing using JUnit"
            }
            post {
                failure {
                    mail to: "s222283975@deakin.edu.au",
                    subject: currentBuild.result,
                    body: "Build failed" 
                }
                success {
                    mail to: "s222283975@deakin.edu.au",
                    subject: currentBuild.result,
                    body: "Build was successfull"
                        
                }
            }
        }
        
        stage('Code Analysis') {
            steps {
                echo "using SonarQube tool to analyse the code."
            }
        }
        
        stage('Security Scan') {
            steps {
                echo "OWASP Dependency-Check Plugin"
            }

            post {
                failure {
                        mail to: "s222283975@deakin.edu.au",
                        subject: currentBuild.result,
                        body: "Build failed"
                }

                success {
                     mail to: "s222283975@deakin.edu.au",
                        subject: currentBuild.result,
                        body: "Build was successful"
                }
            }
        }

        stage('Deploy to Staging') {
            steps {
                echo "Deploying to staging in AWS EC2 server"
            }
        }
        
        stage('Integration Tests on Staging') {
            steps {
                echo "using JUnit for Integration testing"
            }
        }
        
        stage('Deploy to Production') {
            steps {
               echo "Deploying to production in AWS EC2 server"
            }
        }
    }
}
